name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ] # Run on every push
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.1'

  install:
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Install dependencies
      run: npm install

  build:
    runs-on: ubuntu-latest
    needs: install
    
    steps:
    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Output GitHub Pages URL
      run: echo "GitHub Pages deployed at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
